### ISSUE TITLE
Memoized and same test names

### ISSUE THREAD

**Issue by ming13** [spekframework/spek#210] opened 2017-05-29 10:50 UTC
Seems like Spek records `memoized` values based on test names. This way if test names are squashed these values are not recreated and are reused. This can be quite painful if these values can contain some state.

The sample code is below.

```kotlin
import org.jetbrains.spek.api.Spek
import org.jetbrains.spek.api.dsl.context
import org.jetbrains.spek.api.dsl.describe
import org.jetbrains.spek.api.dsl.it
import org.junit.platform.runner.JUnitPlatform
import org.junit.runner.RunWith

@RunWith(JUnitPlatform::class)
class NumbersSpec : Spek({

    val environment by memoized { Environment() }

    describe("squashed test names") {

        /*
         * environment object: net.juno.rd.IdSpec$Environment@687e99d8
         * environment object: net.juno.rd.IdSpec$Environment@687e99d8
         * environment object: net.juno.rd.IdSpec$Environment@2d2ffcb7
         * environment object: net.juno.rd.IdSpec$Environment@2d2ffcb7
         * environment object: net.juno.rd.IdSpec$Environment@762ef0ea
         * environment object: net.juno.rd.IdSpec$Environment@31f9b85e
         */
        listOf(listOf(1, 2, 3), listOf(1), emptyList()).forEach { numbers ->

            val numbersAvailable = numbers.isNotEmpty()

            context("numbers ${if (numbersAvailable) "available" else "not available"}") {

                listOf(true, false).forEach { numbersCondition ->

                    context("numbers condition is $numbersCondition") {

                        beforeEachTest {
                            println("environment object: $environment")
                        }

                        it("mostly works but not exactly") {
                        }
                    }
                }
            }
        }
    }

    describe("unique test names") {

        /*
         * environment object: net.juno.rd.IdSpec$Environment@424e1977
         * environment object: net.juno.rd.IdSpec$Environment@10d68fcd
         * environment object: net.juno.rd.IdSpec$Environment@117e949d
         * environment object: net.juno.rd.IdSpec$Environment@6db9f5a4
         * environment object: net.juno.rd.IdSpec$Environment@5f8edcc5
         * environment object: net.juno.rd.IdSpec$Environment@7b02881e
         */
        listOf(listOf(1, 2, 3), listOf(1), emptyList()).forEach { numbers ->

            context("numbers $numbers") {

                listOf(true, false).forEach { numbersCondition ->

                    context("numbers condition is $numbersCondition") {

                        beforeEachTest {
                            println("environment object: $environment")
                        }

                        it("works") {
                        }
                    }
                }
            }
        }
    }

}) {

    class Environment

}
```

**Comment by raniejade** [comment] 2017-05-29 12:08
By default each `test` will have a unique value, you can alter this behaviour by passing a `CachingMode`.

` val environment by memoized(CachingMode.GROUP) { Environment() }` - each group will have a unique instance.

` val environment by memoized(CachingMode.SCOPE) { Environment() }` - will only have one instance throughout the spec.

**Comment by ming13** [comment] 2017-05-29 12:20
Yep, I understand that, but if you take a look at the comments at the sample code `environment object` stays the same if the test name is the same. The desired behaviour would be to have different objects.

**Comment by raniejade** [comment] 2017-05-29 12:25
Ahh sorry, didn't understand the problem at first. Hmmm, I'll take a loot.

**Comment by raniejade** [comment] 2017-05-29 12:43
Okay the problem is with:

```kotlin
           context("numbers ${if (numbersAvailable) "available" else "not available"}") {

                listOf(true, false).forEach { numbersCondition ->

                    context("numbers condition is $numbersCondition") {

                        beforeEachTest {
                            println("environment object: $environment")
                        }

                        it("mostly works but not exactly") {
                        }
                    }
                }
            }
```

Based on the input: `listOf(1, 2, 3), listOf(1), emptyList()`

The number of groups it creates is 3, however 2 has the same description.

`context(numbers available)` - listOf(1, 2, 3)
`context(numbers available)` - listOf(1)
`context(numbers not available )` - emptyList()

Within a `group` descriptions should be unique. Spek uses the description to create a `UniqueId` for it, if there's a duplicate spek (JUnit 5) will go crazy.

**Comment by ming13** [comment] 2017-05-29 13:04
Yeah, that’s the issue. Does it make sense to generate unique ID based not only on the name but on the declaration fact under the hood in Spek? I guess UUID will do the trick. We are migrating from pre-1.0.0 Spek and it worked there as it seems, because we didn’t have this issue before.

**Comment by raniejade** [comment] 2017-05-29 13:19
Problem is tooling will be broken, It requires to know at first hand the test tree - it deduces the `UniqueId`s based on the code structure. With UUIDS there will be no way the spek plugin to deduce the `UniqueId`s. Until we find a way around it, this will not happen.

**Comment by ming13** [comment] 2017-05-29 13:22
Is it possible to save `UniqueId`-name pair?

BTW failing test run when same group IDs is being detected probably will be useful. Otherwise it is kind of hard to find out the source of the issue.

**Comment by raniejade** [comment] 2017-05-29 13:26
> Is it possible to save UniqueId-name pair?
What do you mean?

> BTW failing test run when same group IDs is being detected probably will be useful. Otherwise it is kind of hard to find out the source of the issue.
Definitely.

**Comment by ming13** [comment] 2017-05-29 13:34
> What do you mean?

If I understand this correctly Spek goes through test declaration, takes group IDs names and generates `UniqueId` based on them. Is it possible to generate UUID every time Spek finds new group ID and associate it with the text description? This way every group declaration will have truly unique ID and it will be possible to determine text description based on it. Sorry if it sounds dumb, I don’t know all details obviously.

> Definitely.

This will be a great Spek kind-of-inspection 👍

**Comment by raniejade** [comment] 2017-05-29 13:55
> If I understand this correctly Spek goes through test declaration, takes group IDs names and generates UniqueId based on them. Is it possible to generate UUID every time Spek finds new group ID and associate it with the text description? This way every group declaration will have truly unique ID and it will be possible to determine text description based on it. Sorry if it sounds dumb, I don’t know all details obviously.

It's the same problem, the spek-idea-plugin needs to know about the generated `UniqueId` in order to work. We could use a UUID but we have to change the idea plugin to compile the spec first and prematurely do the discovery phase, but it feels a bit overkill.

**Comment by artem-zinnatullin** [comment] 2017-05-29 14:06
>spek-idea-plugin needs to know about the generated `UniqueId`

But that's impossible if you have any type of runtime-generated test tree i.e. `listOf(something).forEach { context { … } }`…

What if each node in the tree will have two Ids? One is runtime-generated and strictly unique and used for JUnit5 engine and internally by Spek runtime and other that will be same as statically calculated by spek-idea-plugin?

**Comment by raniejade** [comment] 2017-05-29 14:47
@artem-zinnatullin Yeah, it's a known limitation of the plugin. This doesn't work as well: `it("$someVar bar")`. 

> What if each node in the tree will have two Ids? One is runtime-generated and strictly unique and used for JUnit5 engine and internally by Spek runtime and other that will be same as statically calculated by spek-idea-plugin?

That's an interesting idea, I'll just need a way the map those ids to the proper internal ids. I'll look into it more. :+1:

**Comment by artem-zinnatullin** [comment] 2017-05-29 16:29
@raniejade I think it's totally fine if IntelliJ plugin won't support runtime-generated subtrees but it should definitely be supported by Spek runtime and JUnit5 engine binding.

Maybe you could continue generating UniqueId based on node text description and in case if description is not compile time constant literal — just remove "run" button for that subtree in IntelliJ Plugin?

**Comment by raniejade** [comment] 2017-05-30 02:07
It's definitely supported on runtime, the problem arises when there are duplicates within a group. I still prefer descriptions to be unique w/in a group, are there benefits of allowing it?

**Comment by artem-zinnatullin** [comment] 2017-05-30 07:38
No doubts it works at runtime, we use it :) Memoized does not work though..

If you'll start extracting repeatable subtrees as functions that accept
lambda with SpecBody as a receiver and apply them in same spec subtree it's
very easy to have several non unique descriptions in it and it's a real
life use case from our specs.

**Comment by raniejade** [comment] 2017-05-30 08:35
Okay, next question. What is the expected behaviour of duplicate descriptions? Should we merge them or keep them separated? Merging will be problematic if the state introduced is non-deterministic, meaning each call to either scope creation methods (`test`, `group`, etc...) might result into a different state.

**Comment by artem-zinnatullin** [comment] 2017-05-30 09:46
Runtime (including memoized) should treat them as separate nodes which yeah
means that ids should be generated not only by looking at text description

**Comment by raniejade** [comment] 2017-10-30 10:54
This should be fixed by now, see https://github.com/spekframework/spek/blob/2.x/spek-runtimes/jvm/src/test/kotlin/org/spekframework/spek2/jvm/NonUniquePathTest.kt.

**Closed by raniejade** 2017-10-30 10:54 UTC
Labels: bug

**Comment by artem-zinnatullin** [comment] 2017-10-31 00:08
@raniejade should we add a test that'll check memoized in this scenario?
